import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import StoreProvider from "./global/storeProvider";
import { ThemeProvider } from "next-themes";
import Header2 from "./components/Header2";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  
}>) {
  return (
    <StoreProvider>
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
        {/* <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          > */}
            <Header2 />
            {children}
          {/* </ThemeProvider> */}
        {/* {children} */}
        </body>
    </html>
    </StoreProvider>
  );
}
